from fastapi import APIRouter, status, Depends
from src.db.schemas.chat import ChatRequest, ChatResponse
from src.services.chat_service import ChatService
from src.api.deps import get_chat_service

router = APIRouter()

@router.post(
    "/message",
    response_model=ChatResponse,
    status_code=status.HTTP_200_OK,
    summary="Send message to chatbot",
    response_description="Response generated by the model",
)
def send_message_in_chat(
        request: ChatRequest,
        service: ChatService = Depends(get_chat_service)
) -> ChatResponse:
    """
    Endpoint to process a user's chat message.
    Delegates all logic to the ChatService.
    """
    response_text = service.process_user_message(
        message=request.message,
        model_preference=request.model_preference
    )

    return ChatResponse(response=response_text)