import datetime

from sqlalchemy.orm import Session
from src.db.models import models
from src.db.models.models import Transaction
from src.db.schemas import recurrent as recurrent_schema
from src.utils.enums import RecurrenceFrequency

def create_recurrence(
        db: Session,
        recurrence: recurrent_schema.RecurrentTransactionCreate,
        user_id: int,
        commit: bool = True
) -> models.RecurrentTransaction:
    """
    Create a recurrence rule.

    Args:
        db: Database session
        recurrence: Recurrence schema
        user_id: ID of the user
        commit: Whether to commit immediately (default True)
    """
    db_recurrence = models.RecurrentTransaction(
        user_id=user_id,
        base_transaction_id=recurrence.base_transaction_id,
        recurrence_day=recurrence.recurrence_day,
        frequency=recurrence.frequency,
        is_active=True
    )
    db.add(db_recurrence)

    if commit:
        db.commit()
        db.refresh(db_recurrence)
    else:
        db.flush()
        db.refresh(db_recurrence)

    return db_recurrence

def get_active_recurrences(db: Session, frequency: RecurrenceFrequency = RecurrenceFrequency.MONTHLY):
    """
    Get all active recurrences for a specific frequency.
    """
    return db.query(models.RecurrentTransaction).filter(
        models.RecurrentTransaction.is_active == True,
        models.RecurrentTransaction.frequency == frequency
    ).all()

def get_recurrence_execution_for_period(
        db: Session,
        recurrence_id: int,
        start_date: datetime.date,
        end_date: datetime.date
) -> type[Transaction]:
    """
    Checks if a transaction was already generated by this recurrence ID
    within the specific date range.
    """
    return db.query(models.Transaction).filter(
        models.Transaction.created_by_recurrence_id == recurrence_id,
        models.Transaction.reference_date >= start_date,
        models.Transaction.reference_date <= end_date
    ).first()